/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package missioncontrolleruv1;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class MissionGUI extends javax.swing.JFrame {

    /**
     * Creates new form MissionGUI
     * 
     */
    //public static MissionGUI missionGUI;
    MissionControllerUV missionControllerUV = new MissionControllerUV();
    
    public MissionGUI() {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jTabbed1 = new javax.swing.JTabbedPane();
        jPanelMission = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsole = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        bt_startConnection = new javax.swing.JButton();
        bt_stopConnection = new javax.swing.JButton();
        jTF_ip1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxQuadList = new javax.swing.JComboBox<>();
        jPanelModes = new javax.swing.JPanel();
        jButtonStabilize = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jButtonAltHold = new javax.swing.JButton();
        jButtonLoiter = new javax.swing.JButton();
        jButtonStabilize3 = new javax.swing.JButton();
        jButtonStabilize4 = new javax.swing.JButton();
        jButtonStabilize5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelComm = new javax.swing.JPanel();
        jLabelTitleComm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitleController = new javax.swing.JLabel();
        jComboBox_controllers = new javax.swing.JComboBox<>();
        jProgressBarX = new javax.swing.JProgressBar();
        jProgressBarY = new javax.swing.JProgressBar();
        jProgressBarZ = new javax.swing.JProgressBar();
        jProgressBarZrot = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelDPad = new javax.swing.JLabel();
        jButtonControlX = new javax.swing.JButton();
        jButtonControlY = new javax.swing.JButton();
        jButtonControlB = new javax.swing.JButton();
        jButtonControlA = new javax.swing.JButton();
        jButtonControlStart = new javax.swing.JButton();
        jButtonControlBack = new javax.swing.JButton();
        jButtonControlLJ = new javax.swing.JButton();
        jButtonControlRJ = new javax.swing.JButton();
        jButtonControlRT = new javax.swing.JButton();
        jButtonControlRB = new javax.swing.JButton();
        jButtonControlLB = new javax.swing.JButton();
        jButtonControlLT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelTests = new javax.swing.JPanel();
        jLabelUVlogo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaConsole.setEditable(false);
        jTextAreaConsole.setColumns(20);
        jTextAreaConsole.setLineWrap(true);
        jTextAreaConsole.setRows(5);
        jTextAreaConsole.setFocusable(false);
        jTextAreaConsole.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTextAreaConsole);
        jTextAreaConsole.getAccessibleContext().setAccessibleParent(jTextAreaConsole);

        bt_startConnection.setText("<html><center>Establish<br />Connection</center></html>");
        bt_startConnection.setFocusPainted(false);
        bt_startConnection.setFocusable(false);
        bt_startConnection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_startConnection.setMargin(new java.awt.Insets(2, 2, 2, 2));
        bt_startConnection.setOpaque(false);
        bt_startConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_startConnectionActionPerformed(evt);
            }
        });

        bt_stopConnection.setText("<html><center>Stop<br />Connection</center></html>");
        bt_stopConnection.setFocusPainted(false);
        bt_stopConnection.setFocusable(false);
        bt_stopConnection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_stopConnection.setMargin(new java.awt.Insets(2, 2, 2, 2));
        bt_stopConnection.setOpaque(false);
        bt_stopConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_stopConnectionActionPerformed(evt);
            }
        });

        jTF_ip1.setText("192.168.0.18");
        jTF_ip1.setToolTipText("");

        jLabel1.setText("IP address");

        jComboBoxQuadList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quadrotor 1" }));

        jButtonStabilize.setText("<html><center>Stabilize</center></html>");
        jButtonStabilize.setFocusable(false);
        jButtonStabilize.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonStabilize.setMaximumSize(new java.awt.Dimension(69, 23));
        jButtonStabilize.setMinimumSize(new java.awt.Dimension(69, 23));
        jButtonStabilize.setPreferredSize(new java.awt.Dimension(69, 23));
        jButtonStabilize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStabilizeActionPerformed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Flight Modes");
        jLabel8.setMaximumSize(new java.awt.Dimension(69, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(69, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(69, 14));

        jButtonAltHold.setText("<html><center>Altitude<br />Hold</center></html>");
        jButtonAltHold.setFocusPainted(false);
        jButtonAltHold.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonAltHold.setPreferredSize(new java.awt.Dimension(69, 37));

        jButtonLoiter.setText("Loiter");
        jButtonLoiter.setFocusable(false);
        jButtonLoiter.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonLoiter.setMaximumSize(new java.awt.Dimension(69, 23));
        jButtonLoiter.setMinimumSize(new java.awt.Dimension(69, 23));
        jButtonLoiter.setPreferredSize(new java.awt.Dimension(69, 23));

        jButtonStabilize3.setText("RTL");
        jButtonStabilize3.setFocusable(false);
        jButtonStabilize3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonStabilize3.setMaximumSize(new java.awt.Dimension(69, 23));
        jButtonStabilize3.setMinimumSize(new java.awt.Dimension(69, 23));
        jButtonStabilize3.setPreferredSize(new java.awt.Dimension(69, 23));

        jButtonStabilize4.setText("<html><center>Auto</center></html>");
        jButtonStabilize4.setFocusable(false);
        jButtonStabilize4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonStabilize4.setMinimumSize(new java.awt.Dimension(69, 23));
        jButtonStabilize4.setPreferredSize(new java.awt.Dimension(69, 23));

        jButtonStabilize5.setText("<html><center>Land</center></html>");
        jButtonStabilize5.setFocusable(false);
        jButtonStabilize5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonStabilize5.setMaximumSize(new java.awt.Dimension(69, 23));
        jButtonStabilize5.setMinimumSize(new java.awt.Dimension(69, 23));
        jButtonStabilize5.setPreferredSize(new java.awt.Dimension(69, 23));

        javax.swing.GroupLayout jPanelModesLayout = new javax.swing.GroupLayout(jPanelModes);
        jPanelModes.setLayout(jPanelModesLayout);
        jPanelModesLayout.setHorizontalGroup(
            jPanelModesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModesLayout.createSequentialGroup()
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelModesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModesLayout.createSequentialGroup()
                        .addGroup(jPanelModesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonStabilize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonStabilize3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModesLayout.createSequentialGroup()
                                .addComponent(jButtonStabilize4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStabilize5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelModesLayout.createSequentialGroup()
                                .addComponent(jButtonAltHold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLoiter, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator5))
        );
        jPanelModesLayout.setVerticalGroup(
            jPanelModesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addGroup(jPanelModesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelModesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonStabilize, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLoiter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonAltHold, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStabilize3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStabilize5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStabilize4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_ip1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_stopConnection, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxQuadList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(bt_startConnection, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelModes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_startConnection, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxQuadList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_stopConnection)
                    .addComponent(jTF_ip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
            .addComponent(jPanelModes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMissionLayout = new javax.swing.GroupLayout(jPanelMission);
        jPanelMission.setLayout(jPanelMissionLayout);
        jPanelMissionLayout.setHorizontalGroup(
            jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
        );
        jPanelMissionLayout.setVerticalGroup(
            jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMissionLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        jTabbed1.addTab("Mission Control", jPanelMission);

        jLabelTitleComm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTitleComm.setText("Communication Settings");

        jLabelTitleController.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTitleController.setText("Controller Settings");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("X Axis");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Y Axis");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Z Axis");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Z Rotation");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("D-Pad");
        jLabel6.setToolTipText("");

        jLabelDPad.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelDPad.setText("D-Pad");
        jLabelDPad.setToolTipText("");

        jButtonControlX.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlX.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlX.setText("X");
        jButtonControlX.setFocusable(false);
        jButtonControlX.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlX.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlX.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlX.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlY.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlY.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlY.setText("Y");
        jButtonControlY.setFocusable(false);
        jButtonControlY.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlY.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlY.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlY.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlB.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlB.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlB.setText("B");
        jButtonControlB.setFocusable(false);
        jButtonControlB.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlB.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlB.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlB.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlA.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlA.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlA.setText("A");
        jButtonControlA.setFocusable(false);
        jButtonControlA.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlA.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlA.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlA.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlStart.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlStart.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlStart.setText("Start");
        jButtonControlStart.setFocusable(false);
        jButtonControlStart.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlStart.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlStart.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlStart.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlBack.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlBack.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlBack.setText("Back");
        jButtonControlBack.setFocusable(false);
        jButtonControlBack.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlBack.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlBack.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlBack.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlLJ.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlLJ.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlLJ.setText("LJ");
        jButtonControlLJ.setFocusable(false);
        jButtonControlLJ.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlLJ.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlLJ.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlLJ.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlRJ.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlRJ.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlRJ.setText("RJ");
        jButtonControlRJ.setFocusable(false);
        jButtonControlRJ.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButtonControlRT.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlRT.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlRT.setText("RT");
        jButtonControlRT.setFocusable(false);
        jButtonControlRT.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButtonControlRB.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlRB.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlRB.setText("RB");
        jButtonControlRB.setFocusable(false);
        jButtonControlRB.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButtonControlLB.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlLB.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlLB.setText("LB");
        jButtonControlLB.setFocusable(false);
        jButtonControlLB.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButtonControlLT.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlLT.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlLT.setText("LT");
        jButtonControlLT.setFocusable(false);
        jButtonControlLT.setMargin(new java.awt.Insets(2, 2, 2, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTitleController)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonControlRJ)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonControlX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonControlA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonControlY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_controllers, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonControlLJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGap(56, 56, 56))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonControlLT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonControlLB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDPad)
                                .addComponent(jProgressBarZrot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonControlRT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jButtonControlB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonControlRB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonControlBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonControlStart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(85, 85, 85))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitleController)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_controllers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jProgressBarX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jProgressBarY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jProgressBarZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBarZrot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelDPad))
                .addGap(12, 12, 12)
                .addComponent(jButtonControlY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonControlX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonControlB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonControlLJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonControlA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonControlBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonControlStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonControlRJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonControlRB)
                    .addComponent(jButtonControlLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonControlRT)
                    .addComponent(jButtonControlLT))
                .addGap(32, 32, 32))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanelCommLayout = new javax.swing.GroupLayout(jPanelComm);
        jPanelComm.setLayout(jPanelCommLayout);
        jPanelCommLayout.setHorizontalGroup(
            jPanelCommLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCommLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabelTitleComm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 451, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCommLayout.setVerticalGroup(
            jPanelCommLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanelCommLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitleComm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbed1.addTab("Communication", jPanelComm);

        javax.swing.GroupLayout jPanelTestsLayout = new javax.swing.GroupLayout(jPanelTests);
        jPanelTests.setLayout(jPanelTestsLayout);
        jPanelTestsLayout.setHorizontalGroup(
            jPanelTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        jPanelTestsLayout.setVerticalGroup(
            jPanelTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        jTabbed1.addTab("Tests", jPanelTests);

        jLabelUVlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uvlogo.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gicilogo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbed1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUVlogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbed1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUVlogo)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_startConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_startConnectionActionPerformed
        // TODO add your handling code here:
        MissionControllerUV.startConnection();
    }//GEN-LAST:event_bt_startConnectionActionPerformed

    private void bt_stopConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_stopConnectionActionPerformed
        try {
            // TODO add your handling code here:
            MissionControllerUV.stopConnection();
        } catch (IOException ex) {
            Logger.getLogger(MissionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_stopConnectionActionPerformed

    private void jButtonStabilizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStabilizeActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Do you want to select Stabilize mode?", 
                                  "Choose", 
                                  JOptionPane.YES_NO_OPTION); 
        if (selectedOption == JOptionPane.YES_OPTION) {
            try {
                // TODO add your handling code here:
                MissionControllerUV.requestStateChange("Stabilize");;
            } catch (IOException ex) {
                Logger.getLogger(MissionGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jButtonStabilizeActionPerformed

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt_startConnection;
    public javax.swing.JButton bt_stopConnection;
    public javax.swing.JButton jButtonAltHold;
    public javax.swing.JButton jButtonControlA;
    public javax.swing.JButton jButtonControlB;
    public javax.swing.JButton jButtonControlBack;
    public javax.swing.JButton jButtonControlLB;
    public javax.swing.JButton jButtonControlLJ;
    public javax.swing.JButton jButtonControlLT;
    public javax.swing.JButton jButtonControlRB;
    public javax.swing.JButton jButtonControlRJ;
    public javax.swing.JButton jButtonControlRT;
    public javax.swing.JButton jButtonControlStart;
    public javax.swing.JButton jButtonControlX;
    public javax.swing.JButton jButtonControlY;
    public javax.swing.JButton jButtonLoiter;
    public javax.swing.JButton jButtonStabilize;
    public javax.swing.JButton jButtonStabilize3;
    public javax.swing.JButton jButtonStabilize4;
    public javax.swing.JButton jButtonStabilize5;
    private javax.swing.JComboBox<String> jComboBoxQuadList;
    private javax.swing.JComboBox<String> jComboBox_controllers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabelDPad;
    private javax.swing.JLabel jLabelTitleComm;
    private javax.swing.JLabel jLabelTitleController;
    private javax.swing.JLabel jLabelUVlogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelComm;
    private javax.swing.JPanel jPanelMission;
    private javax.swing.JPanel jPanelModes;
    private javax.swing.JPanel jPanelTests;
    public javax.swing.JProgressBar jProgressBarX;
    public javax.swing.JProgressBar jProgressBarY;
    public javax.swing.JProgressBar jProgressBarZ;
    public javax.swing.JProgressBar jProgressBarZrot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JTextField jTF_ip1;
    private javax.swing.JTabbedPane jTabbed1;
    public javax.swing.JTextArea jTextAreaConsole;
    // End of variables declaration//GEN-END:variables
    
    public void addControllerName(String controllerName){
        jComboBox_controllers.addItem(controllerName);
    }
    
    public int getSelectedControllerName(){
        return jComboBox_controllers.getSelectedIndex();
    }
    
    public void showControllerDisconnected(){
        jComboBox_controllers.removeAllItems();
        jComboBox_controllers.addItem("Controller disconnected!");
    }
}
