/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package missioncontrolleruv;

/**
 *
 * @author Asus
 */
public class MissionGUI extends javax.swing.JFrame {

    /**
     * Creates new form MissionGUI
     */
    public MissionGUI() {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbed1 = new javax.swing.JTabbedPane();
        jPanelMission = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelComm = new javax.swing.JPanel();
        jLabelTitleComm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitleController = new javax.swing.JLabel();
        jComboBox_controllers = new javax.swing.JComboBox<>();
        jProgressBarX = new javax.swing.JProgressBar();
        jProgressBarY = new javax.swing.JProgressBar();
        jProgressBarZ = new javax.swing.JProgressBar();
        jProgressBarZrot = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelDPad = new javax.swing.JLabel();
        jButtonControlTest = new javax.swing.JButton();
        jButtonControlX = new javax.swing.JButton();
        jButtonControlY = new javax.swing.JButton();
        jButtonControlB = new javax.swing.JButton();
        jButtonControlA = new javax.swing.JButton();
        jButtonControlStart = new javax.swing.JButton();
        jButtonControlBack = new javax.swing.JButton();
        jButtonControlLJ = new javax.swing.JButton();
        jButtonControlRJ = new javax.swing.JButton();
        jButtonControlRT = new javax.swing.JButton();
        jButtonControlRB = new javax.swing.JButton();
        jButtonControlLB = new javax.swing.JButton();
        jButtonControlLT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanelMissionLayout = new javax.swing.GroupLayout(jPanelMission);
        jPanelMission.setLayout(jPanelMissionLayout);
        jPanelMissionLayout.setHorizontalGroup(
            jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMissionLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addContainerGap(794, Short.MAX_VALUE))
        );
        jPanelMissionLayout.setVerticalGroup(
            jPanelMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMissionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        jTabbed1.addTab("Mission Control", jPanelMission);

        jLabelTitleComm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTitleComm.setText("Communication Settings");

        jLabelTitleController.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTitleController.setText("Controller Settings");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("X Axis");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Y Axis");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Z Axis");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Z Rotation");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("D-Pad");
        jLabel6.setToolTipText("");

        jLabelDPad.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelDPad.setText("D-Pad");
        jLabelDPad.setToolTipText("");

        jButtonControlTest.setText("Control Test");

        jButtonControlX.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlX.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlX.setText("X");
        jButtonControlX.setFocusable(false);
        jButtonControlX.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlX.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlX.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlX.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlY.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlY.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlY.setText("Y");
        jButtonControlY.setFocusable(false);
        jButtonControlY.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlY.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlY.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlY.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlB.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlB.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlB.setText("B");
        jButtonControlB.setFocusable(false);
        jButtonControlB.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlB.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlB.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlB.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlA.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlA.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlA.setText("A");
        jButtonControlA.setFocusable(false);
        jButtonControlA.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlA.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlA.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlA.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlStart.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlStart.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlStart.setText("Start");
        jButtonControlStart.setFocusable(false);
        jButtonControlStart.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlStart.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlStart.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlStart.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlBack.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlBack.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlBack.setText("Back");
        jButtonControlBack.setFocusable(false);
        jButtonControlBack.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlBack.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlBack.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlBack.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlLJ.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlLJ.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlLJ.setText("LJ");
        jButtonControlLJ.setFocusable(false);
        jButtonControlLJ.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonControlLJ.setMaximumSize(new java.awt.Dimension(21, 21));
        jButtonControlLJ.setMinimumSize(new java.awt.Dimension(21, 21));
        jButtonControlLJ.setPreferredSize(new java.awt.Dimension(21, 21));

        jButtonControlRJ.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlRJ.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlRJ.setText("RJ");
        jButtonControlRJ.setFocusable(false);
        jButtonControlRJ.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButtonControlRT.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlRT.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlRT.setText("RT");
        jButtonControlRT.setFocusable(false);
        jButtonControlRT.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButtonControlRB.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlRB.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlRB.setText("RB");
        jButtonControlRB.setFocusable(false);
        jButtonControlRB.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButtonControlLB.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlLB.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlLB.setText("LB");
        jButtonControlLB.setFocusable(false);
        jButtonControlLB.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButtonControlLT.setBackground(new java.awt.Color(255, 255, 255));
        jButtonControlLT.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonControlLT.setText("LT");
        jButtonControlLT.setFocusable(false);
        jButtonControlLT.setMargin(new java.awt.Insets(2, 2, 2, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTitleController)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonControlTest)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonControlRJ)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonControlX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonControlA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonControlY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonControlLJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGap(56, 56, 56))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonControlLT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonControlLB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDPad)
                                .addComponent(jProgressBarZrot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonControlRT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonControlB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonControlBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonControlStart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(85, 85, 85))
                        .addComponent(jButtonControlRB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox_controllers, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitleController)
                .addGap(4, 4, 4)
                .addComponent(jComboBox_controllers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonControlTest, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jProgressBarX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jProgressBarY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jProgressBarZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBarZrot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelDPad))
                .addGap(12, 12, 12)
                .addComponent(jButtonControlY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonControlX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonControlB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonControlLJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonControlA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonControlBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonControlStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonControlRJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonControlRB)
                    .addComponent(jButtonControlLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonControlRT)
                    .addComponent(jButtonControlLT))
                .addGap(32, 32, 32))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanelCommLayout = new javax.swing.GroupLayout(jPanelComm);
        jPanelComm.setLayout(jPanelCommLayout);
        jPanelCommLayout.setHorizontalGroup(
            jPanelCommLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCommLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabelTitleComm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCommLayout.setVerticalGroup(
            jPanelCommLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanelCommLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitleComm)
                .addContainerGap(428, Short.MAX_VALUE))
        );

        jTabbed1.addTab("Communication", jPanelComm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbed1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MissionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MissionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MissionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MissionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MissionGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonControlA;
    public javax.swing.JButton jButtonControlB;
    public javax.swing.JButton jButtonControlBack;
    public javax.swing.JButton jButtonControlLB;
    public javax.swing.JButton jButtonControlLJ;
    public javax.swing.JButton jButtonControlLT;
    public javax.swing.JButton jButtonControlRB;
    public javax.swing.JButton jButtonControlRJ;
    public javax.swing.JButton jButtonControlRT;
    public javax.swing.JButton jButtonControlStart;
    public javax.swing.JButton jButtonControlTest;
    public javax.swing.JButton jButtonControlX;
    public javax.swing.JButton jButtonControlY;
    private javax.swing.JComboBox<String> jComboBox_controllers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabelDPad;
    private javax.swing.JLabel jLabelTitleComm;
    private javax.swing.JLabel jLabelTitleController;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelComm;
    private javax.swing.JPanel jPanelMission;
    public javax.swing.JProgressBar jProgressBarX;
    public javax.swing.JProgressBar jProgressBarY;
    public javax.swing.JProgressBar jProgressBarZ;
    public javax.swing.JProgressBar jProgressBarZrot;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbed1;
    // End of variables declaration//GEN-END:variables
    
    public void addControllerName(String controllerName){
        jComboBox_controllers.addItem(controllerName);
    }
    
    public int getSelectedControllerName(){
        return jComboBox_controllers.getSelectedIndex();
    }
    
    public void showControllerDisconnected(){
        jComboBox_controllers.removeAllItems();
        jComboBox_controllers.addItem("Controller disconnected!");
    }
}
